name: Build new release and push it to github

on:
  issues:
    types:
      - opened
  
defaults:
  run:
    shell: bash

jobs:
  check-requirements:
    runs-on: ubuntu-latest

    steps:
      - name: Clone hp100 and releases repositories without checking out working copies
        env:
          ISSUE_OBJ: ${{ github.event.issue.title }}
        run: |
          echo "$ISSUE_OBJ"
