# The idea is that every day at midnight (i.e. 0 0 * * * in cron syntax), we
# fetch main repos (for now only the hp100 one) and see if there any new releses.
# These are marked with a tag formatted as follows `release-vX.Y`. If there is one,
# we build, encrypt and upload it to the repo.
#
# NOTE: source its based on https://github.com/ethereum/solc-bin/blob/gh-pages/.github/workflows/nightly-emscripten.yml

name: Build new release and push it to github

on: [push]
#   schedule:
#     - cron: "0 0 * * *"

env:
  RELEASE_BRANCH: release
  COMMITTER_NAME: release-gh-action
  COMMITTER_EMAIL: releases@helvest.ch
  
defaults:
  run:
    shell: bash

jobs:
  check-requirements:
    runs-on: ubuntu-latest
    outputs:
      is-release: ${{ env.IS_RELEASE }}
      release-version: ${{ env.RELEASE_VERSION }}
      release-already-exists: ${{ env.RELEASE_ALREADY_EXISTS }}

    steps:
      - name: Clone hp100 and releases repositories without checking out working copies
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git clone --no-checkout --branch "$RELEASE_BRANCH" "https://${ACCESS_TOKEN}@github.com/helvest-systems-gmbh/hp100.git" hp100/
          git clone --no-checkout "https://github.com/${GITHUB_REPOSITORY}.git" releases/

      - name: Determine new release version
        run: |
          cd hp100/
          ls -al
          last_tag="$(git describe --tags --abbrev=0)"
          is_release=$([[ $last_tag == release/* ]] && echo "true" || echo "false")
          echo $is_release

          echo "IS_RELEASE=${is_release}" >> $GITHUB_ENV
          test $is_release == "true" && echo "RELEASE_VERSION=$(echo $last_tag | tr -d "release/")" >> $GITHUB_ENV

      - name: Check if there's already a release with the same version
        if: "outputs.is_release == 'true'"
        run: |
          cd releases/
          matching_release_in_the_repo="$(git ls-files "hp100/hp100-firmware-v${RELEASE_VERSION}.hex")"
          release_already_exists="$(test -n "$matching_release_in_the_repo" && echo true || echo false)"

          # There's no way to just stop a job without failing and that would spam everyone with
          # spurious e-mail notifications about the failure. Instead we have to make do with `if`s.
          echo "RELEASE_ALREADY_EXISTS=${release_already_exists}" >> $GITHUB_ENV
          
  build-release:
    runs-on: ubuntu-latest
    needs: check-requirements
    
    if: "needs.check-requirements.outputs.is_release == 'true'"
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "helvest-systems-gmbh/hp100"
          ref: ${{ env.RELEASE_BRANCH }}
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: recursive
          path: hp100
          
      - name: Install AVR toolchain
        run: sudo apt-get install binutils gcc-avr avr-libc
      
      - name: Check dependencies version
        run: avr-g++ --version
        
      - name: Build firmware release
        run: |
          cd hp100
          make
      
      - name: Encrypt firmware release
        env:
          ENCRYPTION_KEY: ${{ secrets.RELEASE_ENCRYPTION_KEY }}
        run: |
          cd hp100
          npm install -g @prgx/cli
          prgx encrypt main.hex -k "$ENCRYPTION_KEY" -o hp100-firmware.hex

      - name: Upload release hex as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: hp100-firmware.hex
          path: hp100/hp100-firmware.hex

  add-release-and-push:
    runs-on: ubuntu-latest
    needs: 
      - check-requirements
      - build-release

    env:
      FULL_RELEASE_VERSION: ${{ needs.build-release.outputs.full-release-version }}

    if: "needs.check-requirements.outputs.release-already-exists == 'false'"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.TARGET_BRANCH }}
          path: "releases"

      - name: Download firmware artifact
        uses: actions/download-artifact@v2
        with:
          name: hp100-firmware.hex

      - name: Set committer name and e-mail
        run: |
          cd releases/
          git config --local user.name "$COMMITTER_NAME"
          git config --local user.email "$COMMITTER_EMAIL"

      - name: Run add-release-and-push.sh
        run: |
          cd releases/
          ./add-release-and-push.sh ../hp100-firmware.hex "$FULL_RELEASE_VERSION"
